# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "25.4.0"

package:
  name: "lightdg"
  version: 25.4.0

source:
  - path: ../lightdg
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package . -o ${PREFIX}/lib/mojo/lightdg.mojopkg

requirements:
  run:
    - max >=25.4.0,<25.5.0

about:
  homepage: https://github.com/Dhinagaran-s/lightdg
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/Dhinagaran-s/lightdg
