[project]
authors = ["saviorand"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/mojo-community"]
description = "Simple and fast HTTP framework for Mojo!"
name = "lightbug_http"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = "MODULAR_MOJO_NIGHTLY_IMPORT_PATH=$CONDA_PREFIX/lib/mojo rattler-build build --no-include-recipe"

[dependencies]
max = ">=24.5.0.dev2024083105,<25"
gojo = "0.1.2"