[workspace]
authors = ["Dhinagaran-s <dhinagaran1411@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
name = "code"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]
# Define workspace-wide tasks if needed
format = { cmd = "magic run mojo format -l 120 lightdg" }
test = { cmd = "magic run mojo test -I . tests/lightdg" }
integration_tests_py = { cmd = "bash scripts/integration_test.sh" }
integration_tests_external = { cmd = "magic run mojo test -I . tests/integration" }
integration_tests_udp = { cmd = "bash scripts/udp_test.sh" }
bench = { cmd = "magic run mojo -I . benchmark/bench.mojo" }
bench_server = { cmd = "bash scripts/bench_server.sh" }
build = { cmd = "rattler-build build --recipe recipes -c https://conda.modular.com/max -c conda-forge --skip-existing=all", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

[dependencies]
max = ">=25.5.0,<26"
mojo = ">=25.5.0,<26"
requests = ">=2.32.3,<3"
fastapi = ">=0.115.3,<0.116"

[environments]
default = { solve-group = "default" }
unit-tests = { tasks = ["test"], solve-group = "default" }
integration-tests = { tasks = ["integration_tests_py", "integration_tests_external", "integration_tests_udp"], solve-group = "default" }
bench = { tasks = ["bench", "bench_server"], solve-group = "default" }
publish = { tasks = ["publish"], solve-group = "default" }
build = { tasks = ["build"], solve-group = "default" }
