[workspace]
authors = ["Dhinagaran-s <dhinagaran1411@gmail.com>"]
channels = ["conda-forge","https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
name = "code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.5.0,<26"
mojo = ">=25.5.0,<26"







