# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "lightbug_http"
  version: 0.1.0

source:
  - path: ./lightbug_http

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package . -o ${PREFIX}/lib/mojo/lightbug_http.mojopkg

requirements:
  run:
    - max >= 24.5.0.dev2024083105
    - gojo == 0.1.1

# tests:
#   - script:
#       # commands to run to test the package. If any of the commands
#       # returns with an error code, the test is considered failed.
#       - mojo test test/
#       - ls -la info/recipe
#       - cp ${PREFIX}/lib/mojo/lightbug_http.mojopkg info/recipe/test/lightbug_http.mojopkg
#       - mojo test info/recipe/test/

#     # requirements:
#     #   run:
#     #     - mojo

#     files:
#       # Extra files to be copied to the test directory from the "work directory"
#       source:
#         - ../src/
#         - ../test/

about:
  homepage: https://github.com/saviorand/lightbug_http
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo that builds on best practice from systems programming, such as the Golang and Rust.
  repository: https://github.com/saviorand/lightbug_http
