[project]
authors = ["saviorand"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Simple and fast HTTP framework for Mojo!"
name = "lightbug_http"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.4.0,<25"

[pypi-dependencies]
magic_test = { git = "https://github.com/saviorand/testmagic", rev="main"}