version: '3'
services:
  lightbug:
    build:
      context: .
      args:
        - DEFAULT_SERVER_PORT=${DEFAULT_SERVER_PORT}
    ports:
      - "${DEFAULT_SERVER_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - APP_ENTRYPOINT=${APP_ENTRYPOINT}
