version: '3'
services:
  lightbug:
    build:
      context: .
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - APP_ENTRYPOINT=${APP_ENTRYPOINT}
