name: Branch workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  bench:
    uses: ./.github/workflows/bench.yml

  package:
    uses: ./.github/workflows/package.yml

  docker:
    needs: package
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        type=ref,event=branch
        type=sha,prefix={{branch}}-
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
