name: Default pipeline

on:
  push:
    branches: ['*']
  workflow_dispatch:
  pull_request:
    branches: ['*']

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the test suite
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
          magic run mojo run_tests.mojo

  package:
    name: Create package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the package command
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
          magic run mojo package lightbug_http -o lightbug_http.mojopkg
      
      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: lightbug_http.mojopkg
          tag: latest-build
          overwrite: true
  
  publish:
    name: Publish package
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install magic
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
      
      - name: Build package for target platform
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
          CONDA_BLD_PATH: ${{ runner.workspace }}/.rattler
        run: |
          # Temporary method to fetch the rattler binary.
          RATTLER_BINARY="rattler-build-aarch64-apple-darwin"
          if [[ $TARGET_PLATFORM == "linux-64" ]]; then RATTLER_BINARY="rattler-build-x86_64-unknown-linux-musl"; fi
          curl -SL --progress-bar https://github.com/prefix-dev/rattler-build/releases/latest/download/${RATTLER_BINARY} -o rattler-build
          chmod +x rattler-build

          # Build and push
          magic run build --target-platform=$TARGET_PLATFORM
          magic run publish
