name: Default pipeline

on:
  push:
    branches: ['*']
  workflow_dispatch:
  pull_request:
    branches: ['*']

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the test suite
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
          magic install
          magic run mojo run_tests.mojo

  package:
    name: Create package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the package command
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
          magic install
          magic run mojo package lightbug_http -o lightbug_http.mojopkg
      
      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: lightbug_http.mojopkg
          tag: latest-build
          overwrite: true
