name: Main workflow

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  package:
    uses: ./.github/workflows/package.yml
  
  publish:
    uses: ./.github/workflows/publish.yml
    secrets:
      PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
  
  docker:
    needs: [package, publish]
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        type=raw,value=edge
        type=raw,value=stable
        type=sha,prefix=stable-
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
